sudo: required
dist: trusty

os:
- osx
- linux

addons:
  apt:
    packages:
    - build-essential
    - libxext-dev
    - libxtst-dev
    - libxkbfile-dev

language: node_js
node_js:
- '6'

before_install:
- npm install -g gulp
- npm install

cache:
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

script:
- npm run travis
